README.md
Signed-off-by: Sida Shen <shenstan1@gmail.com>
=> README.md minor fixes

README.md
Signed-off-by: Sida Shen <shenstan1@gmail.com>
=> README.md add connect to sr

pkg/starrockscluster_controller_test.go
* fixes #37
Signed-off-by: Kevin Xiaohua Cai <caixiaohua@starrocks.com>
=> fixes #37, fix ut failure

pkg/be_controller/be_pod.go
fix be pod error log-storage-name and annotations
Signed-off-by: haiming <dxheming@163.com>
=> fix be pod error log-storage-name and annotations

Makefile, deploy/starrocks.com_starrocksclusters.yaml
* make `deploy/starrocks.com_starrocksclusters.yaml` a simplified version without field description
* fixes #93
=> fix crd yaml too long to apply by kubectl

pkg/sub_controller/cn/cn_controller.go
=> fix log positional parameters

.github/workflows/release-chart.yml, helm-charts/.helmignore, helm-charts/LICENSE, helm-charts/README.md, helm-charts/charts/kube-starrocks/.helmignore, helm-charts/charts/kube-starrocks/Chart.yaml, helm-charts/charts/kube-starrocks/README.md, helm-charts/charts/kube-starrocks/crds/starrocks.com_starrocksclusters.yaml, helm-charts/charts/kube-starrocks/templates/NOTES.txt, helm-charts/charts/kube-starrocks/templates/_helpers.tpl, helm-charts/charts/kube-starrocks/templates/starrocks-operator/clusterrole.yaml, helm-charts/charts/kube-starrocks/templates/starrocks-operator/clusterrolebinding.yaml, helm-charts/charts/kube-starrocks/templates/starrocks-operator/deployment.yaml, helm-charts/charts/kube-starrocks/templates/starrocks-operator/leader-election-role-binding.yaml, helm-charts/charts/kube-starrocks/templates/starrocks-operator/leader-election-role.yaml, helm-charts/charts/kube-starrocks/templates/starrocks-operator/service_account.yaml, helm-charts/charts/kube-starrocks/templates/starrocks/beconfigmap.yaml, helm-charts/charts/kube-starrocks/templates/starrocks/cnconfigmap.yaml, helm-charts/charts/kube-starrocks/templates/starrocks/feconfigmap.yaml, helm-charts/charts/kube-starrocks/templates/starrocks/starrockscluster.yaml, helm-charts/charts/kube-starrocks/templates/tests/test-connection.yaml, helm-charts/charts/kube-starrocks/values.yaml
converge helm charts and operator into one signle repo to simplify the development and maintenance.
The chart are copied from `helm-charts` this commit: https://github.com/StarRocks/helm-charts/commit/8c5b526267a113d42e636d1256d07a979c032d99
=> Merge helm charts into the operator repo

doc/initialize_root_password_howto.md
Add instructions for initializing password configuration methods.
=> Add instructions for initializing password configuration methods

index.yaml, scripts/artifacts.sh
=> move index yaml to root

deploy/operator.yaml, helm-charts/charts/kube-starrocks/Chart.yaml, helm-charts/charts/kube-starrocks/templates/starrocks-operator/deployment.yaml, helm-charts/charts/kube-starrocks/values.yaml, index.yaml, pkg/k8sutils/templates/pod/spec.go, pkg/k8sutils/templates/pod/spec_test.go, scripts/artifacts.sh
=> update some files for release v1.7.1

helm-charts/charts/kube-starrocks/templates/_helpers.tpl, helm-charts/charts/kube-starrocks/templates/init-pwd/configmap.yaml, helm-charts/charts/kube-starrocks/templates/init-pwd/job.yaml, helm-charts/charts/kube-starrocks/templates/starrocks-operator/deployment.yaml, helm-charts/charts/kube-starrocks/templates/starrocks/starrockscluster.yaml, helm-charts/charts/kube-starrocks/values.yaml
1.Add time zone settings.
2.Fixed issue where Secret could not find during help upgrade.
=> Add time zone settings and fixed issue where Secret could not find during helm upgrade.

helm-charts/charts/kube-starrocks/charts/starrocks/templates/starrockscluster.yaml, helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml, helm-charts/charts/kube-starrocks/values.yaml
=> allow user to add attributes on datadog log annotations

pkg/k8sutils/k8sutils.go, pkg/starrockscluster_controller.go, pkg/sub_controller/cn/cn_controller.go
=> add ResourceVersion before update service resources

cmd/main.go
=> set resync period

.gitignore, deploy/operator.yaml, doc/integration/integration-prometheus-grafana.md, helm-charts/charts/kube-starrocks/Chart.yaml, helm-charts/charts/kube-starrocks/charts/operator/Chart.yaml, helm-charts/charts/kube-starrocks/charts/operator/values.yaml, helm-charts/charts/kube-starrocks/charts/starrocks/Chart.yaml, helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml, helm-charts/charts/kube-starrocks/values.yaml, index.yaml, scripts/artifacts.sh, scripts/migrate-chart-value/main_test.go
=> update some scripts for v1.8.0

helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml, helm-charts/charts/kube-starrocks/values.yaml, pkg/apis/starrocks/v1/starrockscluster_types.go, pkg/k8sutils/load/metadata.go, pkg/k8sutils/load/metadata_test.go, pkg/k8sutils/templates/deployment/spec.go, pkg/k8sutils/templates/pod/spec.go, pkg/k8sutils/templates/pod/spec_test.go, pkg/k8sutils/templates/statefulset/spec.go, pkg/starrockscluster_controller.go, pkg/sub_controller/be/be_controller.go, pkg/sub_controller/be/be_pod.go, pkg/sub_controller/cn/cn_controller.go, pkg/sub_controller/cn/cn_pod.go, pkg/sub_controller/fe/fe_controller.go, pkg/sub_controller/fe/fe_pod.go, pkg/sub_controller/feproxy/feproxy_controller.go, pkg/sub_controller/subcontroller.go
=> remove restart logic

pkg/starrockscluster_controller.go, pkg/sub_controller/be/be_controller.go, pkg/sub_controller/be/be_controller_test.go, pkg/sub_controller/cn/cn_controller.go, pkg/sub_controller/cn/cn_controller_test.go, pkg/sub_controller/fe/fe_controller.go, pkg/sub_controller/fe/fe_controller_test.go, pkg/sub_controller/feproxy/feproxy_controller.go, pkg/sub_controller/subcontroller.go
=> remove related k8s resources when BeSpec/CnSpec is deleted

config/crd/bases/starrocks.com_starrocksclusters.yaml, deploy/starrocks.com_starrocksclusters.yaml, doc/README.md, doc/api.md, doc/mount_external_configmaps_or_secrets_howto.md, helm-charts/charts/kube-starrocks/charts/starrocks/templates/starrockscluster.yaml, helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml, helm-charts/charts/kube-starrocks/values.yaml, pkg/apis/starrocks/v1/component_type.go, pkg/apis/starrocks/v1/starrockscluster_types.go, pkg/common/hash/hash_test.go, pkg/k8sutils/templates/pod/spec.go, pkg/k8sutils/templates/pod/spec_test.go
=> support subpath for configmaps and secrets

cmd/main.go, helm-charts/charts/kube-starrocks/charts/operator/templates/deployment.yaml, helm-charts/charts/kube-starrocks/charts/operator/values.yaml, helm-charts/charts/kube-starrocks/values.yaml
=> add namespace flag to make operator watch resources in a single namespace

CHANGELOG.md, deploy/operator.yaml, helm-charts/charts/kube-starrocks/Chart.yaml, helm-charts/charts/kube-starrocks/charts/operator/Chart.yaml, helm-charts/charts/kube-starrocks/charts/operator/values.yaml, helm-charts/charts/kube-starrocks/charts/starrocks/Chart.yaml, helm-charts/charts/kube-starrocks/values.yaml, index.yaml
=> change related docs to release v1.8.3

pkg/sub_controller/feproxy/feproxy_configmap.go
=> [Bugfix] fe proxy failed in multiple fe pods

doc/local_installation_how_to.md, scripts/local-install-values.yaml, scripts/local-install.sh
=> [Docs] install starrocks locally

doc/change_root_password_howto.md
Add description about how to update root password by using helm chart.
=> [Doc] update change_root_password_howto.md

README_ZH-CN.md
=> [Documentation] update README_ZH-CN.md

helm-charts/charts/warehouse/templates/configmap.yaml, pkg/starrockswarehouse_controller.go
export args for operator helm chart and update warehouse status
=> [Enhancement] update warehouse status

config/crd/bases/starrocks.com_starrocksclusters.yaml, deploy/starrocks.com_starrocksclusters.yaml, pkg/apis/starrocks/v1/starrockscluster_types.go, pkg/controllers/starrockscluster_controller.go, pkg/controllers/starrockswarehouse_controller.go, pkg/subcontrollers/cn/cn_controller.go, pkg/subcontrollers/subcontroller.go
=> [Enhancement] use StarRocksCluster State to log errors when subController failed

helm-charts/charts/kube-starrocks/charts/starrocks/templates/starrockscluster.yaml
Correct typo in storageSpec name condition in starrocksCnSpec of Helm chart
=> chore:Correct typo in storageSpec

pkg/k8sutils/k8sutils.go
=> [Bugfix] Use patch not update method to modify statefulset and deployment

pkg/common/resource_utils/service.go, pkg/common/resource_utils/service_test.go, pkg/subcontrollers/cn/cn_controller.go
=> [Bugfix] Add annotations content to svc object before calculate service hash

examples/starrocks/README.md, examples/starrocks/deploy_a_starrocks_cluster_with_be_capabilities.yaml, helm-charts/charts/kube-starrocks/charts/starrocks/templates/starrockscluster.yaml, helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml, helm-charts/charts/kube-starrocks/values.yaml
=> starrocks helm:enable capabilities in starrocksBeSpec

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md, .github/workflows/action-make-test.yml, Makefile
=> [Documentation] add pull_request_template.md

.gitignore, helm-charts/charts/kube-starrocks/charts/starrocks/templates/init-pwd/job.yaml, helm-charts/charts/kube-starrocks/charts/starrocks/templates/starrockscluster.yaml, helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml, helm-charts/charts/kube-starrocks/values.yaml, pkg/subcontrollers/be/be_controller.go, pkg/subcontrollers/cn/cn_controller.go, pkg/subcontrollers/fe/fe_controller.go
Fixed bugs when test main branch for releasing v1.9.2
=> [BugFix] Fix bugs when test main branch

doc/mount_persistent_volume_howto.md
Make sure the example can be executed in GKE environment.
=> [Documentation] Complete examples in mount_persistent_volume_howto.md

examples/starrocks/deploy_a_starrocks_cluster_with_cn.yaml, examples/starrocks/starrocks-fe-and-be.yaml
Make sure these examples are deployable and the data is persistent.
=> [Documentation] Update examples linked from starrocks.io

config/crd/bases/starrocks.com_starrocksclusters.yaml, config/crd/bases/starrocks.com_starrockswarehouses.yaml, pkg/k8sutils/k8sutils.go, pkg/k8sutils/k8sutils_test.go, pkg/k8sutils/templates/pod/mount_test.go
wrong compare in `k8sutils.go`
```
if v.Name == newMountPath
```
=> [BugFix] Fix mountPath

helm-charts/charts/kube-starrocks/charts/operator/templates/deployment.yaml, helm-charts/charts/kube-starrocks/charts/operator/values.yaml, helm-charts/charts/kube-starrocks/values.yaml
In a high-security k8s environment, the default securityContext configuration may not meet the requirements and custom securityContext configurations are needed.
=> [Enhancement] Support to customize securityContext for Operator

Dockerfile
Update the base image in Dockerfile
=> [Chore] Update Dockerfile

pkg/subcontrollers/cn/cn_pod.go
Fix URL which is used to get FE fearures
=> [WIP][BugFix] Fix URL which is used to get FE features

CHANGELOG.md, deploy/operator.yaml, doc/api.md, helm-charts/charts/kube-starrocks/Chart.yaml, helm-charts/charts/kube-starrocks/charts/operator/Chart.yaml, helm-charts/charts/kube-starrocks/charts/operator/values.yaml, helm-charts/charts/kube-starrocks/charts/starrocks/Chart.yaml, helm-charts/charts/kube-starrocks/values.yaml, helm-charts/charts/warehouse/Chart.yaml, index.yaml
=> [Chore] Prepare for v1.9.6

helm-charts/charts/kube-starrocks/charts/starrocks/templates/starrockscluster.yaml
Please provide a detailed description of the changes you have made. Include the motivation for these changes, and any
additional context that may be important.
#520 
=> Issue #520

doc/deploy_warehouse_howto.md
Add a documentation about how to deploy warehouse.
Fixes: #365
=> [WIP][Documentation] Add deploy_warehouse_howto.md

doc/deploy_warehouse_howto.md, pkg/subcontrollers/cn/cn_mysql.go, pkg/subcontrollers/cn/cn_mysql_test.go
=> [BugFix] Add namespace to service domain

config/crd/bases/starrocks.com_starrocksclusters.yaml, config/crd/bases/starrocks.com_starrockswarehouses.yaml, deploy/starrocks.com_starrocksclusters.yaml, deploy/starrocks.com_starrockswarehouses.yaml, pkg/apis/starrocks/v1/starrockscluster_types.go, pkg/apis/starrocks/v1/starrockswarehouse_types.go
Add version information to crd
=> Add version information to CRD

helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml, helm-charts/charts/kube-starrocks/values.yaml
=> [Document] Add usage for affinity

CHANGELOG.md, config/crd/bases/starrocks.com_starrocksclusters.yaml, config/crd/bases/starrocks.com_starrockswarehouses.yaml, deploy/operator.yaml, deploy/starrocks.com_starrocksclusters.yaml, deploy/starrocks.com_starrockswarehouses.yaml, doc/api.md, helm-charts/charts/kube-starrocks/Chart.yaml, helm-charts/charts/kube-starrocks/charts/operator/Chart.yaml, helm-charts/charts/kube-starrocks/charts/operator/values.yaml, helm-charts/charts/kube-starrocks/charts/starrocks/Chart.yaml, helm-charts/charts/kube-starrocks/values.yaml, helm-charts/charts/warehouse/Chart.yaml, index.yaml, pkg/apis/starrocks/v1/starrockscluster_types.go, pkg/apis/starrocks/v1/starrockswarehouse_types.go
=> [Chore] Prepare for v1.9.7

doc/README.md, doc/build_your_own_container_image_howto.md
=> [Documentation] Build your own container image

helm-charts/charts/kube-starrocks/charts/starrocks/templates/starrockscluster.yaml, helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml, helm-charts/charts/kube-starrocks/values.yaml
=> [Enhancement] support service annotations for fe proxy

go.mod, pkg/common/resource_utils/configmap.go, pkg/common/resource_utils/configmap_test.go, pkg/k8sutils/k8sutils.go, pkg/k8sutils/k8sutils_test.go, pkg/subcontrollers/be/be_controller.go, pkg/subcontrollers/be/be_controller_test.go, pkg/subcontrollers/be/be_pod.go, pkg/subcontrollers/cn/cn_controller.go, pkg/subcontrollers/cn/cn_controller_test.go, pkg/subcontrollers/cn/cn_pod.go, pkg/subcontrollers/fe/fe_controller.go, pkg/subcontrollers/fe/fe_controller_test.go, pkg/subcontrollers/fe/fe_pod.go, pkg/subcontrollers/feproxy/feproxy_configmap.go
=> [Enhancement] Respect the component conf definition in configmaps

deploy/operator.yaml, helm-charts/charts/kube-starrocks/charts/operator/templates/clusterrole.yaml, helm-charts/charts/kube-starrocks/charts/operator/templates/role.yaml
=> [BugFix] Add update permission for starrocksclusters/finalizers resource

doc/load_data_using_stream_load_howto.md
see https://github.com/StarRocks/starrocks-kubernetes-operator/blob/b8b2d58b7c2e9c06240e5eebd0ec12670f5fb315/helm-charts/charts/kube-starrocks/values.yaml#L1086C3-L1086C23
=> [Documentation] Fix spelling errors

helm-charts/charts/kube-starrocks/charts/starrocks/templates/init-pwd/job.yaml, helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml, helm-charts/charts/kube-starrocks/values.yaml
=> [Enhancement] Properly set password when deployed by Argo CD

helm-charts/charts/kube-starrocks/charts/starrocks/templates/starrockscluster.yaml, helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml, helm-charts/charts/kube-starrocks/values.yaml
=> [Enhancement] Introduce a new sidecarsMap configuration option to allow merge sidecarswhen using helm chart

pkg/k8sutils/k8sutils.go, pkg/subcontrollers/cn/cn_mysql.go
=> [Enhancement] Support to delete statefulset for warehouse

cmd/config/config.go, cmd/main.go, pkg/k8sutils/templates/pod/mount.go
=> [BugFix] Add parameter to control whether add a hash suffix for volume name

helm-charts/charts/kube-starrocks/charts/starrocks/templates/servicemonitor.yaml, helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml, helm-charts/charts/kube-starrocks/values.yaml
Support request param for serviceMonitor
=> [Enhancement] Support request param for serviceMonitor

helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml, helm-charts/charts/kube-starrocks/values.yaml
=> [Chore] make the commnets in values.yaml more readable

pkg/common/log/log.go, pkg/controllers/starrockscluster_controller.go, pkg/subcontrollers/be/be_controller.go, pkg/subcontrollers/be/be_controller_test.go, pkg/subcontrollers/cn/cn_controller.go, pkg/subcontrollers/cn/cn_controller_test.go, pkg/subcontrollers/fe/fe_controller.go, pkg/subcontrollers/fe/fe_controller_test.go, pkg/subcontrollers/feproxy/feproxy_controller.go, pkg/subcontrollers/subcontroller.go
Fix some todo tasks about renaming the name of methods
=> [Chore] Rename the name of some methods

config/crd/bases/starrocks.com_starrocksclusters.yaml, config/crd/bases/starrocks.com_starrockswarehouses.yaml, deploy/starrocks.com_starrocksclusters.yaml, deploy/starrocks.com_starrockswarehouses.yaml, helm-charts/charts/kube-starrocks/charts/starrocks/templates/starrockscluster.yaml, helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml, helm-charts/charts/kube-starrocks/values.yaml, pkg/apis/starrocks/v1/component_type.go, pkg/apis/starrocks/v1/starrockscluster_types.go, pkg/k8sutils/templates/statefulset/spec.go
=> [Enhancement] Support podManagementPolicy
