- .dockerignore
- Dockerfile
- README.md
For micro-service k8s deployment, tt's preferred to use [distroless](https://github.com/GoogleContainerTools/distroless)  as it's much smaller in terms of size and has less vulnerabilities. 
(Ref: [centos vulnerability report ](https://snyk.io/test/docker/centos%3A7))
- User [docker multi-stage build](https://docs.docker.com/build/building/multi-stage/) to build binary in a hermetic environment
- Package operator binary into distroless image
- Added instructions for building and publishing docker image
- Build the image with both distroless and centos and compares side-by-side
```
$ docker image ls
REPOSITORY                  TAG       IMAGE ID       CREATED        SIZE
starrocks/operator       centos   dd9ff6dc9389   5 seconds ago     253MB
starrocks/operator   distroless   976cfe591ce8 …
```
> Package operator binary into distroless image

- doc/change_root_password_howto.md
fix typo. should be 'Prerequisites'.
> doc: Update change_root_password_howto.md

- helm-charts/charts/kube-starrocks/templates/_helpers.tpl
- helm-charts/charts/kube-starrocks/templates/starrocks/starrockscluster.yaml
- helm-charts/charts/kube-starrocks/values.yaml
在fe和be的storageSpec增加logStorageSize，当配置此参数时，fe和be的log存储使用pvc管理，替代默认的emptyDir。增加此配置是为了在某些情况下，保存be的日志，以分析be崩溃的原因。
> 增加logStorageSize配置,当增加此配置时,fe和be的log存储使用pvc管理

- pkg/sub_controller/be/be_controller_test.go
- pkg/sub_controller/cn/cn_controller_test.go
- pkg/sub_controller/fe/fe_controller_test.go
- pkg/sub_controller/fe/service.go
* use statefulset selector for fe service pod selector. not the full pods labels
* fixes #91
> fix wrong fe service labels

- helm-charts/charts/kube-starrocks/templates/init-pwd/configmap.yaml
- helm-charts/charts/kube-starrocks/templates/init-pwd/job.yaml
- helm-charts/charts/kube-starrocks/templates/starrocks/starrockscluster.yaml
- helm-charts/charts/kube-starrocks/values.yaml
在部署starrocks时，增加配置初始化密码的能力。在部署时，可以设置：
```
initPassword: 
enabled: true
password: "password"
```
设置此参数后，部署时会提交一个job，尝试修改fe-0的密码，同时，fe、be、cn会自动添加环境变量：
```
- name: "MYSQL_PWD"
valueFrom:
secretKeyRef:
name: {{ template "kube-starrocks.name" . }}-credential
key: password
```
按照以上配置完成starrocks的部署时，root账号的初始化密码会被修改为指定值。
> 在部署starrocks时，增加初始化密码的能力。

- helm-charts/charts/kube-starrocks/templates/init-pwd/configmap.yaml
- helm-charts/charts/kube-starrocks/templates/init-pwd/job.yaml
Fix issue #183: Modify the execution time of the job to only execute the job when executing 'help install'.
> Modify the execution time of the job to only execute the job when executing 'helm install'. 

- pkg/k8sutils/templates/pod/spec.go
- pkg/k8sutils/templates/pod/spec_test.go
In some serverless k8s env ,there is no status.hostIP field, and we do not use hostIp in StarRocks， so remove it.
> [Bugfix] support k8s env which has no status.hostIP field

- examples/starrocks/deploy_a_starrocks_cluster_with_cn.yaml
- examples/starrocks/starrocks-fe-and-be.yaml
> [Docs] add starrocks-fe-and-be.yaml

- pkg/common/resource_utils/service.go
- pkg/common/resource_utils/service_test.go
- pkg/sub_controller/fe/fe_controller.go
Fixes: https://github.com/StarRocks/starrocks-kubernetes-operator/issues/287
> [Enhancement] add appProtocol in fe service

- helm-charts/charts/kube-starrocks/charts/operator/templates/_helpers.tpl
- helm-charts/charts/kube-starrocks/charts/operator/templates/clusterrole.yaml
- helm-charts/charts/kube-starrocks/charts/operator/templates/clusterrolebinding.yaml
- helm-charts/charts/kube-starrocks/charts/operator/templates/deployment.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/templates/_helpers.tpl
- helm-charts/charts/kube-starrocks/charts/starrocks/templates/beconfigmap.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/templates/cnconfigmap.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/templates/feconfigmap.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/templates/init-pwd/job.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
Fixes: #275 
If starrocks.initPassword.enabled is true, and the value of starrocks.starrocksCluster.name is set, it will cause an issue. When the value starrocks.starrocksCluster.name is set, the service hostname will follows while the hostname inside the initpwd still using the chart name.
> [Bugfix] remove chart function kube-starrocks.name

- pkg/sub_controller/feproxy/feproxy_configmap.go
This is the original snippet in nginx.conf
```
location @handle_redirect {
set $redirect_uri '$upstream_http_location';
proxy_pass $redirect_uri;
proxy_set_header Expect $http_expect;
proxy_pass_request_body on;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
error_page 307 = @handle_redirect;
}
```
When Nginx forwards requests to Leader FE and then BE, it follows the above  Nginx configuration. Because proxy_pass_request_body is set to true, Nginx sends requests to Leader FE. When FE returns 307, Nginx forwards the request to BE. At this point, the data cached in Nginx is lost, causing the error.
```
2023/11/03 14:35:39 [error] 23#23: *23 sendfile() failed (32: Broken pipe) while sending request to …
```
> [Bugfix] set proxy_pass_request_body off when redirect to FE

- pkg/apis/starrocks/v1/auto_scale.go
- pkg/k8sutils/k8sutils.go
- pkg/k8sutils/k8sutils_test.go
- pkg/subcontrollers/cn/cn_controller.go
when remove hpa resource, removing the dependency of StarRocksCluster Status.
fixes: #263
> [BugFix] Remove HPA resource when CN spec is removed

- pkg/k8sutils/templates/service/spec.go
> [BugFix] Remove annotations from search service

- pkg/k8sutils/k8sutils.go
Fixes: #384 
This is an update strategy based on the JSON Merge Patch standard. JSON Merge Patch merges the submitted JSON object into the existing resource object. If a field exists in the submitted JSON object, then the value of this field in the resource object will be replaced. If a field does not exist in the submitted JSON object, then the value of this field in the resource object will remain unchanged.
> [BugFix] use Patch not Update to modify service object

- helm-charts/charts/kube-starrocks/charts/starrocks/templates/starrockscluster.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
Fixes: https://github.com/StarRocks/starrocks-kubernetes-operator/issues/395
> [Enhancement] support use map to define feEnvVars/beEnvVars to do merge on multiple values files

- pkg/k8sutils/k8sutils.go
- pkg/k8sutils/k8sutils_test.go
- pkg/subcontrollers/be/be_controller.go
- pkg/subcontrollers/cn/cn_controller.go
- pkg/subcontrollers/fe/fe_controller.go
If scale to 1, Operator will report an error. 
```
k get starrocksclusters.starrocks.com kube-starrocks
NAME             PHASE    FESTATUS   BESTATUS   CNSTATUS   FEPROXYSTATUS
kube-starrocks   failed   running               running
k get starrocksclusters.starrocks.com kube-starrocks -oyaml | grep reason
reason: 'error from FE controller: the replicas of statefulset kube-starrocks-fe can not be scaled to 1'
```
> [Enhancement] disable FE scale to 1

- helm-charts/charts/kube-starrocks/charts/operator/templates/deployment.yaml
- helm-charts/charts/kube-starrocks/charts/operator/values.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/templates/init-pwd/job.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/templates/starrockscluster.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
Add imagePullSecrets and affinity fields for some helm charts:
1.starrocksOperator add the imagePullSecrets and affinity fields.
2.fe-proxy add the imagePullSecrets field.
3.init-pwd job reuse the "FE" field, including both the affinity and imagePullSecrets fields.
> Add imagePullSecrets and affinity fields for some helm charts

- config/crd/bases/starrocks.com_starrocksclusters.yaml
- config/crd/bases/starrocks.com_starrockswarehouses.yaml
- deploy/starrocks.com_starrocksclusters.yaml
- deploy/starrocks.com_starrockswarehouses.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
- pkg/apis/starrocks/v1/load_type.go
- pkg/common/resource_utils/service.go
- pkg/common/resource_utils/service_test.go
> [Enhancement] Prefer to use containerPort to export service node port

- helm-charts/charts/kube-starrocks/charts/starrocks/templates/_helpers.tpl
- helm-charts/charts/kube-starrocks/charts/starrocks/templates/starrockscluster.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
> [BugFix] Allow to remove some resources limit, like cpu

- helm-charts/charts/kube-starrocks/charts/starrocks/templates/_helpers.tpl
- helm-charts/charts/kube-starrocks/charts/starrocks/templates/starrockscluster.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
In the individual spec definitions of the sub-components, there are indeed many fields with the same name, such as image, imagePullSecrets, nodeSelector, schedulerName. Generally, the contents of these fields are consistent in the individual spec definitions of the sub-components. 
Fixes: #424 
> [Enhancement] Define some default values uniformly

- helm-charts/charts/kube-starrocks/charts/starrocks/templates/_helpers.tpl
when execute `helm upgrade`, helm report the following error:
```
W0130 19:07:13.003223   81804 warnings.go:70] unknown field "spec.starRocksBeSpec.resources"
W0130 19:07:13.003243   81804 warnings.go:70] unknown field "spec.starRocksCnSpec.resources"
W0130 19:07:13.003245   81804 warnings.go:70] unknown field "spec.starRocksFeSpec.resources"
```
This is because functions defined in `_helpers.tpl` has error, include `starrockscluster.fe.resources`, `starrockscluster.be.resources` and `starrockscluster.cn.resources`.
> [BugFix] Fix unknown field "spec.starRocksBeSpec.resources" error

- doc/README.md
- doc/least_permission_to_deploy_starrocks_howto.md
You can install the StarRocks operator and StarRocks cluster by kubectl or helm. No matter which way you choose, you
may need a permissions.
> [Documentation] Add doc/least_permission_to_deploy_starrocks_howto.md

- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
> [Enhancement] Eliminate the Helm warning caused by the different types of feEnvVars, beEnvVars, and cnEnvVars

- helm-charts/charts/kube-starrocks/charts/starrocks/templates/_helpers.tpl
- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
Backgroud information: https://github.com/StarRocks/starrocks-kubernetes-operator/issues/390#issuecomment-1918509571
In order to run StarRocks on a read-only file system, users need a volume to mount at `/opt/starrocks/fe` or `/opt/starrocks/be`.  But helm chart do not support to specify a mount path.
Fixes: #390 
> [Enhancement] allow user to specify mount path

- helm-charts/charts/kube-starrocks/charts/starrocks/templates/servicemonitor.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
If there are multiple prometheus instances in k8s environment,  user need to add label to specify the concrete instance.
> [Enhancement] Allow user to add labels on serviceMonitor

- helm-charts/charts/kube-starrocks/charts/starrocks/templates/starrockscluster.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
Add datadog_profiling options in Helm chart to simplify the settings to enable dd profiling.
[Please list any related issues and link them here.](https://github.com/StarRocks/starrocks-kubernetes-operator/issues/423)
-----Test Plan----
1. `helm lint`
2. `helm template` with settings on/off, and see the diff of `helm template starrocks .`
3. apply the new `StarRocksCluster` yaml 
----Revision 2 Test Plan-------
1. turn on be/fe profiling, no difference compared with revision 1;
2. Add `starrocksBeSpec.capabilities` in values to confirm it's merged correctly
```
capabilities:
add:
- PERFMON
- SYS_PTRACE
drop:
- SYS_ADMIN
``` …
> [Feature][issue-423] add datadog profiling to SR Helm

- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
- pkg/common/resource_utils/configmap.go
In the latest StarRocks version, the port names for BE and CN have been modified. The good news is that the old port names can still be used. However, if users use the new port names, Operators may not recognize them, leading to Operators potentially using default ports as liveness and readiness ports. This could result in container startup failures.
> [Enhancement] support be_http_port and be_port in conf

- helm-charts/charts/kube-starrocks/charts/starrocks/templates/_helpers.tpl
- helm-charts/charts/kube-starrocks/charts/starrocks/templates/init-pwd/job.yaml
A scenario that requires modifying the container listening query port:
1. The source cluster is deployed on virtual machines, while the target cluster is deployed on k8s. External access to the internal IP of k8s is not possible, but pods within k8s can access external IPs.
2. The migration tool is deployed outside of k8s. The StarRocks cluster on k8s is exposed through /etc/host (frontend domain name, node IP of k8s) + NodePort.
3. In the cross-cluster migration tool, use the port obtained from `Show Frontend` for recording in Frontend. At the same time, use this port to access the target cluster (instead of configuring target_fe_query_port).
4. The target cluster pulls data from the source cluster.
chart( …
> [BugFix] Ensure query port can be configured in init-password job

- helm-charts/charts/kube-starrocks/charts/starrocks/templates/init-pwd/job.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
> [Enhancement] support annotations and image filed for init-password job

- pkg/k8sutils/k8sutils.go
- pkg/subcontrollers/cn/cn_controller.go
Fixes: #420 
the root cause is In GKE environment, the Minor version is not a number, like v1.27.3-gke.100.
```
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3-gke.100", GitCommit:"6466b51b762a5c49ae3fb6c2c7233ffe1c96e48c", GitTreeState:"clean", BuildDate:"2023-06-23T09:27:28Z", GoVersion:"go1.20.5 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```
How do I fix the issue? In StarRocksCluster CR status, there are fields about HPA.
```
horizontalScaler:
name: kube-starrocks-cn-autoscaler
version: v2
```
we can first use this `version` to delete the HPA resource.
> [BugFix] Fix HPA deletion failed on GKE

- doc/deploy_multiple_clusters_howto.md
- helm-charts/charts/kube-starrocks/charts/operator/templates/role.yaml
- helm-charts/charts/kube-starrocks/charts/operator/templates/rolebinding.yaml
- helm-charts/charts/kube-starrocks/charts/operator/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
When operator is limited to watches a single namespace, We can remove the clusterrole and clusterrolebinding, and use role and rolebinding instead. 
> [Enhancement] Use Role and Rolebinding instead when operator watches a specified namespace

- helm-charts/charts/kube-starrocks/charts/starrocks/templates/init-pwd/job.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
when .Values.starrocksFESpec.tolerations or .Values.starrocksCluster.componentValues.tolerations is configured, the FE init-password Job will respect this.
This is the rendered result:
```
kind: Job
metadata:
name: starrocks-initpwd
namespace: starrocks
spec:
template:
spec:
tolerations:
- effect: NoSchedule
key: key
operator: Equal|Exists
value: value
```
> [Enhancement] Support tolerations for init-password job

- pkg/k8sutils/k8sutils.go
- pkg/k8sutils/k8sutils_test.go
In cloud provider, the minor version may be like "28+" from alibaba cloud. So we need to remove the non-digit characters.
this is from alibaba cloud
```
{
"major": "1",
"minor": "28+",
"gitVersion": "v1.28.3-aliyun.1",
"gitCommit": "7b6ea506b6deb03bac7aaeb10f6ee0a99004b147",
"gitTreeState": "clean",
"buildDate": "2023-10-19T07:10:40Z",
"goVersion": "go1.20.10",
"compiler": "gc",
"platform": "linux/amd64"
}
```
and this is from eks cloud
```
{
"major": "1",
"minor": "27",
"gitVersion": "v1.27.8-gke.1067004",
"gitCommit": "6f460c12ad45abb234c18ec4f0ea335a1203c415",
"gitTreeState": "clean",
"buildDate": "2024-01-04T22:48:32Z",
"goVersion": "go1.20.11 X:boringcrypto",
"compiler": "gc",
"platform": "linux/amd64"
}
```
> [Enhancement] clean minor version of k8s

- pkg/k8sutils/k8sutils.go
- pkg/k8sutils/k8sutils_test.go
If we mistakenly determine the type of HPA, we will receive an error message similar  to "no matches for kind 'HorizontalPodAutoscaler' in version 'autoscaling/v2beta2'".
This error cannot be identified through apierrors, and using string comparison to determine if it is this error is not a good approach. Therefore, our solution is to always switch to another version of HPA for deletion.
> [BugFix] Try to use different version to delete HPA

- helm-charts/charts/kube-starrocks/charts/starrocks/templates/starrockscluster.yaml
- helm-charts/charts/warehouse/templates/starrockswarehouse.yaml
> [BugFix] Make sure xx-config-hash is a valid string

- helm-charts/charts/kube-starrocks/charts/starrocks/templates/starrockscluster.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
Please provide a detailed description of the changes you have made. Include the motivation for these changes, and any
additional context that may be important.
-------------------
* default
```
+    fe: true # change to 'true' to enable profiling on FE pods;
+    be: true # change to 'true' to enable profiling on BE pods;
+    configMode: "service"
===>
$ helm template starrocks . | grep 'config.mode'
admission.datadoghq.com/config.mode: service
admission.datadoghq.com/config.mode: service
```
* `socket`
```
+ …
```
> [issue481]expose datadog config.mode in helm chart

- doc/cn/logging_and_related_configurations_howto.md
- doc/logging_and_related_configurations_howto.md
- doc/mount_persistent_volume_howto.md
- examples/starrocks/deploy_a_starrocks_cluster_with_all_features.yaml
- examples/starrocks/deploy_a_starrocks_cluster_with_persistent_storage.yaml
- pkg/apis/starrocks/v1/starrockscluster_types.go
- scripts/migrate-chart-value/main_test.go
Deploy the following YAML file in a GKE environment:
```
apiVersion: starrocks.com/v1
kind: StarRocksCluster
metadata:
name: starrockscluster-sample
namespace: starrocks
labels:
cluster: starrockscluster-sample
spec:
starRocksFeSpec:
image: "starrocks/fe-ubuntu:3.2-latest"
storageVolumes:
- name: fe-storage-meta
storageSize: 10Gi
storageClassName: ""
mountPath: /opt/starrocks/fe/meta
- name: fe-storage-log
storageSize: 5Gi
storageClassName: ""
mountPath: /opt/starrocks/fe/log
starRocksBeSpec:
image: "starrocks/be-ubuntu:3.2-latest"
replicas: 1
storageVolumes:
- name: be-storage-data
storageSize: 1Gi
storageClassName: ""
mountPath: /opt/starrocks/be/storage
- name: be-storage-log
storageSize: 1Gi
storageClassName: ""
mountPath: /opt/starrocks/be/log
```
Got the following error:
```
k get …
```
> [Documentation] Remove `storageClassName: ""` Configuration

- helm-charts/charts/kube-starrocks/charts/starrocks/templates/resources.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
When deploying StarRocks using Helm chart, users often need additional configurations in their environment. For example, in an EKS environment, they may need to deploy SecurityGroupPolicy and TargetGroupBinding. The user's solution is to download the chart, modify it, which poses a significant challenge when upgrading the chart.
> [Enhancement] Support to customize resources for starrocks helm chart

- .github/workflows/action-golangci-lint.yml
- .github/workflows/action-make-test.yml
- go.mod
when execute `make test`, it will need to install setup-envtest binary. Encountered the following error.
```
go: sigs.k8s.io/controller-runtime/tools/setup-envtest@latest (in sigs.k8s.io/controller-runtime/tools/setup-envtest@v0.0.0-20240327193027-21368602d84b): go.mod:3: invalid go version '1.22.0': must match format 1.23
make: *** [envtest] Error 1
```
need to upgrade to golang version 1.22 to solve this problem.
> [Enhancement] Upgrade golang version to 1.22

- helm-charts/charts/kube-starrocks/Chart.yaml
Fix the following error:
```
$ helm lint .
==> Linting .
[ERROR] /tmp/kube-starrocks: chart metadata is missing these dependencies: operator,starrocks
Error: 1 chart(s) linted, 1 chart(s) failed
```
> [BugFix] Add dependencies for kube-starrocks chart

- helm-charts/charts/kube-starrocks/charts/starrocks/templates/_helpers.tpl
- helm-charts/charts/kube-starrocks/charts/starrocks/templates/beconfigmap.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/templates/cnconfigmap.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/templates/feconfigmap.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/templates/starrockscluster.yaml
- helm-charts/charts/warehouse/templates/_helpers.tpl
- helm-charts/charts/warehouse/templates/cnconfigmap.yaml
- helm-charts/charts/warehouse/templates/starrockswarehouse.yaml
Currently, there are two formats of template YAML files. This PR aims to standardize the format of YAML files, especially the indentation.
The main changes are in the config and annotation fields, so I compared them using the following values.yaml for rendering. **The contents before and after are exactly the same.**
```
starrocksCluster:
enabledBe: true
enabledCn: true
starrocksFESpec:
config: |
LOG_DIR = ${STARROCKS_HOME}/log
DATE = "$(date +%Y%m%d-%H%M%S)"
JAVA_OPTS="-Dlog4j2.formatMsgNoLookups=true -Xmx8192m -XX:+UseMembar -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=7 -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSClassUnloadingEnabled -XX:-CMSParallelRemarkEnabled -XX:CMSInitiatingOccupancyFraction=80 -XX:SoftRefLRUPolicyMSPerMB=0 …
```
> [Chore] format some template yaml files in helm chart

- helm-charts/charts/kube-starrocks/charts/starrocks/templates/init-pwd/configmap.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/templates/init-pwd/job.yaml
In order to support deploying multiple StarRocks clusters to a single K8s namespace, we need to ensure that all resource names are unique. Currently, the name of the configmap for "fe init-password" is hardcoded.
> [BugFix] Make multiple fe init password job can be deployed in one namespace

- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
- pkg/k8sutils/templates/pod/spec.go
- pkg/subcontrollers/be/be_pod.go
Changing the default volume name to be-data, and it will affect users who did not persist data.
The reason why we need to change the volume name is that the helm chart uses the `-data` as suffix. Keeping the same suffix will make user easy to use feature, like `init-containers` and `sidecars`.
> [BugFix] Use the same suffix for be volume for CR and chart user

- cmd/main.go
- pkg/controllers/controllers.go
- pkg/controllers/controllers_test.go
Use namespaced scope permission to list warehouses
#512 
> [BugFix] Use namespaced scope permission to list warehouses

- doc/load_data_using_stream_load_howto.md
> [Documentation] Update doc/load_data_using_stream_load_howto.md

- helm-charts/charts/kube-starrocks/charts/operator/templates/NOTES.txt
- helm-charts/charts/kube-starrocks/charts/starrocks/templates/NOTES.txt
- helm-charts/charts/kube-starrocks/templates/NOTES.txt
Fix the helm chart url in NOTES.txt
> update url for helm chart

- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
I was confused by the wording about HPA and replicas, I shortened it and I hope it makes sense to everyone, please check.
I also reordered the resources sections to that all of them are in the same order as the FE (requests then limits).
> update comments and order

- examples/starrocks/deploy_a_starrocks_cluster_running_in_shared_data_mode.yaml
- examples/starrocks/deploy_a_starrocks_cluster_with_all_features.yaml
- examples/starrocks/deploy_a_starrocks_cluster_with_custom_configurations.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
Due to the inclusion of JAVA_OPTS_FOR_JDK_9, JAVA_OPTS_FOR_JDK_11, and JAVA_OPTS in the default values.yaml, their coexistence may cause confusion. According to the logic of the code in [start_fe.sh](https://github.com/StarRocks/starrocks/blob/522c03c6016d9fecc5b45f15f29d88a29df15463/bin/start_fe.sh#L111-L131), the one that takes effect is always JAVA_OPTS_FOR_JDK_11.
Therefore, we will remove JAVA_OPTS_FOR_JDK_9 and JAVA_OPTS_FOR_JDK_11 from values.yaml and set the value of JAVA_OPTS to the value of JAVA_OPTS_FOR_JDK_11.
https://github.com/StarRocks/starrocks/issues/46481
> [Chore] remove JAVA_OPTS_FOR_JDK_9 and JAVA_OPTS_FOR_JDK_11 env from fe config

- config/crd/bases/starrocks.com_starrocksclusters.yaml
- config/crd/bases/starrocks.com_starrockswarehouses.yaml
- deploy/starrocks.com_starrocksclusters.yaml
- deploy/starrocks.com_starrockswarehouses.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/templates/_helpers.tpl
- helm-charts/charts/kube-starrocks/charts/starrocks/templates/starrockscluster.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
- pkg/apis/starrocks/v1/load_type.go
- pkg/apis/starrocks/v1/zz_generated.deepcopy.go
- pkg/k8sutils/templates/pod/spec.go
This PR adds support for using Pod Topology Spread Constraints. This is useful when trying to distribute the scheduling of pods evenly across failure domains such as nodes or availability zones. In many situations this cannot be done with simple Affinity controls.
> feat: add support for TopologySpreadConstraints

- helm-charts/charts/kube-starrocks/charts/starrocks/templates/_helpers.tpl
- helm-charts/charts/kube-starrocks/charts/starrocks/templates/starrockscluster.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
Add in helm chart possibility to add spill_dir storage configuration.
#535 
> feat: :sparkles: add spill storage in be/cn config

- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
- pkg/apis/starrocks/v1/starrockscluster_types.go
- pkg/k8sutils/templates/pod/mount.go
- pkg/k8sutils/templates/pod/mount_test.go
- pkg/k8sutils/templates/statefulset/spec.go
> [Enhancement] If hostPath is set, the storage class will be considered as hostPath

- pkg/common/resource_utils/service.go
when loadBalancerSourceRanges  field is updated, service should be updated. 
> [BugFix] LoadBalancerSourceRanges field should be used in componnet hash

- .golangci.yml
- pkg/subcontrollers/feproxy/feproxy_configmap.go
> [BugFix] Fix FE proxy will fail when FE external service is recreated

- config/crd/bases/starrocks.com_starrocksclusters.yaml
- config/crd/bases/starrocks.com_starrockswarehouses.yaml
- examples/starrocks/deploy_a_starrocks_cluster_with_all_features.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
- pkg/apis/starrocks/v1/load_type.go
- pkg/k8sutils/templates/pod/probe.go
- pkg/k8sutils/templates/pod/probe_test.go
if user specify failure seconds, and its value it 0, operator will remove the related probe
Fixes: #565
> [Enhancement] Support to disable probe

- helm-charts/charts/kube-starrocks/charts/starrocks/templates/_helpers.tpl
- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
https://github.com/StarRocks/starrocks-kubernetes-operator/issues/494
with values1.yaml, run 
```
helm template --debug kube-starrocks --values kube-starrocks/values.yaml --values kube-starrocks/values-1.yaml
```
```
starrocks:
starrocksFESpec:
configyaml:
query_port: 9031
foo: FEAdditionalValue
additonal: values
starrocksBeSpec:
configyaml:
be_port: 9061
foo: BEAdditionalValue
starrocksCluster:
enabledCn: true
starrocksCnSpec:
configyaml:
heartbeat_service_port: 9051
foo: CNAdditionalValue
```
Got 
with template below, a minor change in the configyaml values generate totally different hash value
```
fe-config-hash: "{{template "starrockscluster.fe.config.hash" . }}"
be-config-hash: "{{template "starrockscluster.be.config.hash" . }}"
cn-config-hash: "{{template …
```
> [helm]support config override in starrocksFESpec/starrocksBeSpec/starrocksCnSpec

- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
When user use Helm Chart to deploy a StarRocks Cluster, the `logStorageSize` value for BE/CN is 1Gi by default. It is too small, and the problem is that when user encounter a problem with BE/CN, they can't get the latest logs!
BE/CN will rotate logs when the size of logs is greater than 10Gi by default. So Allocating 20GB for log storage and 1TB for data storage is more reasonable.
> [Bugfix] Use a reasonable volume size for logging for BE/CN

- helm-charts/charts/kube-starrocks/charts/starrocks/templates/starrockscluster.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
Support multiple data volumes on helm chart
This show how to configure multiple volumes for BE/CN.
```
spec:
starrocksCnSpec:
storageSpec:
logStorageSize: 1Gi
name: cn-storage
storageSize: 100Gi
storageCount: 3    # we want to mount 3 volumes and each volume size is 100Gi
config: |
sys_log_level = INFO
thrift_port = 9060
webserver_port = 8040
heartbeat_service_port = 9050
brpc_port = 8060
storage_root_path = /opt/starrocks/cn/storage0;/opt/starrocks/cn/storage1;/opt/starrocks/cn/storage2   # mount them
spec:
starrocksBeSpec:
storageSpec:
logStorageSize: 1Gi
name: be-storage
storageSize: 100Gi
storageCount: 2   # we want to mount 2 volumes and each volume size is 100Gi
config: |
be_port = 9060
webserver_port = 8040
heartbeat_service_port = 9050
brpc_port = 8060
sys_log_level = INFO …
```
> [Enhancement] Support multiple data volumes on helm chart

- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
Fix Comment about how to disable probe
> [BugFix] Fix Comment about how to disable probe

- config/crd/bases/starrocks.com_starrocksclusters.yaml
- config/crd/bases/starrocks.com_starrockswarehouses.yaml
- deploy/starrocks.com_starrocksclusters.yaml
- deploy/starrocks.com_starrockswarehouses.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/templates/starrockscluster.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
- pkg/apis/starrocks/v1/component_type.go
- pkg/apis/starrocks/v1/component_type_test.go
- pkg/apis/starrocks/v1/load_type.go
- pkg/apis/starrocks/v1/starrockscluster_types.go
- pkg/apis/starrocks/v1/zz_generated.deepcopy.go
- pkg/k8sutils/templates/statefulset/spec.go
- pkg/k8sutils/templates/statefulset/spec_test.go
- pkg/subcontrollers/be/be_controller.go
- pkg/subcontrollers/cn/cn_controller.go
- pkg/subcontrollers/fe/fe_controller.go
see https://github.com/StarRocks/starrocks-kubernetes-operator/issues/592
> [Enhancement] Support Update Strategy for FE/BE/CN component

- pkg/subcontrollers/feproxy/feproxy_configmap.go
StarRocks has released a new version, 3.3.6, which has a bug: for Stream Load requests, FE forcibly requires setting the 100-continue request header, which belongs to the HTTP 1.1 protocol, but Nginx defaults to using the HTTP 1.0 protocol for forwarding, causing Stream Load requests sent to feproxy to fail. 
StarRocks will fix this issue in future versions, but for feproxy users, adding the proxy_http_version 1.1 setting will be compatible with this defect in version 3.3.6.
See https://github.com/StarRocks/starrocks/pull/53010 and https://github.com/StarRocks/starrocks/pull/52582
> [BugFix] set proxy_http_version 1.1

- helm-charts/charts/kube-starrocks/charts/starrocks/templates/starrockscluster.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
In Helm Chart, capabilities field needs to be supported for FE
> [BugFix] In Helm Chart, capabilities field needs to be supported for FE

- helm-charts/charts/kube-starrocks/charts/starrocks/templates/starrockscluster.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
Add support for custom log and spill storage class names
> [Enhancement] Add support for custom log and spill storage class names

- .golangci.yml
- cmd/config/config.go
- cmd/main.go
- helm-charts/charts/kube-starrocks/charts/operator/templates/deployment.yaml
- helm-charts/charts/kube-starrocks/charts/operator/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
- pkg/subcontrollers/feproxy/feproxy_configmap.go
https://github.com/StarRocks/starrocks/issues/49984
We expose a parameter for operator to allow users to specify the dns domain suffix in k8s.
verify the modification:
1. sample configuration for nginx.conf
```
pid   /tmp/nginx.pid;
worker_processes 4;
include /usr/share/nginx/modules/*.conf;
events {
worker_connections 256;
}
http {
sendfile            on;
tcp_nopush          on;
tcp_nodelay         on;
keepalive_timeout   65;
types_hash_max_size 2048;
client_max_body_size 0;
ignore_invalid_headers off;
underscores_in_headers on;
proxy_read_timeout 600s;
proxy_http_version 1.1;
client_body_temp_path /tmp/client_temp;
proxy_temp_path       /tmp/proxy_temp_path;
fastcgi_temp_path     /tmp/fastcgi_temp;
uwsgi_temp_path       /tmp/uwsgi_temp;
scgi_temp_path        /tmp/scgi_temp; …
```
> [BugFix] support to run fe-proxy under customize cluster domain instead of using default one: cluster.local

- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
Fix comment in values.yaml. see https://github.com/StarRocks/starrocks-kubernetes-operator/pull/594#discussion_r1861177782
> [Documentation] Fix comment in values.yaml

- doc/cn/logging_and_related_configurations_howto.md
- doc/logging_and_related_configurations_howto.md
- doc/mount_persistent_volume_howto.md
- examples/starrocks/deploy_a_starrocks_cluster_with_all_features.yaml
- examples/starrocks/deploy_a_starrocks_cluster_with_cn.yaml
- examples/starrocks/deploy_a_starrocks_cluster_with_persistent_storage.yaml
- examples/starrocks/starrocks-fe-and-be.yaml
- pkg/controllers/starrockscluster_controller_test.go
- pkg/k8sutils/k8sutils.go
- pkg/k8sutils/k8sutils_test.go
- pkg/subcontrollers/fe/fe_controller_reconcile_test.go
Please provide a detailed description of the changes you have made. Include the motivation for these changes, and any
additional context that may be important.
#611 
If this PR is included:
```
volumes:
- name: be1-data
persistentVolumeClaim:
claimName: be1-data-kube-starrocks-be-0
- name: be-log
persistentVolumeClaim:
claimName: be-log-kube-starrocks-be-0
- name: be0-data
persistentVolumeClaim:
claimName: be0-data-kube-starrocks-be-0
- configMap:
defaultMode: 420
name: kube-starrocks-be-cm
name: kube-starrocks-be-cm
```
> [Bugfix] Do not create the default data storage volume when deploying be with multiple volumes

- .golangci.yml
- helm-charts/charts/kube-starrocks/charts/starrocks/templates/starrockscluster.yaml
- pkg/common/resource_utils/statefulset.go
- Removed unnecessary quotes around `maxUnavailable` in `starrockscluster.yaml` to ensure proper YAML parsing and value interpretation.
- Added `updateStrategy` to the `hashStatefulsetObject` struct in `statefulset.go` to include update strategy in the hash calculation.
Fixes #615
> [BugFix] Fix StatefulSet Update Strategy Handling

- helm-charts/charts/kube-starrocks/charts/starrocks/templates/init-pwd/job.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
Add in helm chart possibility to add resources configuration for the init_password pod.
We are using openshift, on our cluster we have some kyverno rules set and the need-containers-ressources rules is applied.
We wanted to change the default password but the init_job container coudln't be deployed because the limits/requests wasn't set.
> feat: add resources option for init_job

- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
Change the default value of runAsNonRoot to true
> [Documentation] add comment for runAsNonRoot

- config/crd/bases/starrocks.com_starrocksclusters.yaml
- config/crd/bases/starrocks.com_starrockswarehouses.yaml
- deploy/starrocks.com_starrocksclusters.yaml
- deploy/starrocks.com_starrockswarehouses.yaml
- doc/api.md
- helm-charts/charts/kube-starrocks/charts/starrocks/templates/starrockscluster.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
- helm-charts/charts/warehouse/templates/starrockswarehouse.yaml
- helm-charts/charts/warehouse/values.yaml
- pkg/apis/starrocks/v1/load_type.go
- pkg/apis/starrocks/v1/zz_generated.deepcopy.go
- pkg/common/resource_utils/service.go
- pkg/common/resource_utils/service_test.go
- pkg/k8sutils/templates/service/spec.go
- pkg/k8sutils/templates/service/spec_test.go
- pkg/subcontrollers/be/be_controller.go
- pkg/subcontrollers/cn/cn_controller.go
- pkg/subcontrollers/fe/fe_controller.go
Currently adding K8s service annotations are supported but not labels. Support service labels through the following changes:
- Update CRD definitions in `config/crd/bases/` and `deploy/`
- Update Helm chart templates and values for `helm-charts/charts/kube-starrocks/` and `helm-charts/charts/warehouse/`
- Update `pkg/apis/starrocks/v1/`
- Update `pkg/common/resource_utils/service` and `pkg/k8sutils/templates/service/spec` to handle labels
- Still support default labels generated by operator
- Update subcontrollers so that external service has labels but internal labels don't
https://github.com/StarRocks/starrocks-kubernetes-operator/issues/625
chart( …
> Support service labels

- helm-charts/charts/kube-starrocks/charts/starrocks/templates/init-pwd/job.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
This PR adds the ability for the init-pwd job to configure the job's pod annotations. 
The change was motivated by a need to pass annotations to the pod of the job to disable isito proxy from keeping the job from not completing.
> [Enhancement] Init pwd job pod annotations

- pkg/k8sutils/templates/pod/spec.go
Please provide a detailed description of the changes you have made. Include the motivation for these changes, and any
additional context that may be important.
> [BugFix] Support podLabels in FeProxy component

- helm-charts/charts/kube-starrocks/charts/starrocks/templates/servicemonitor.yaml
- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
allow an endpoint to authenticate over basic authentication, which can access more StarRocks metrics.
> [Enhancement] Support basicAuth for serviceMonitor

- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
- pkg/k8sutils/templates/pod/spec.go
Starting from StarRocks version 3.4.2, StarRocks supports the -g parameter to further support graceful shutdown. The purpose of this PR is to introduce this parameter. For older versions of StarRocks, this parameter will be ignored.
> [Feanture] Enable graceful shutdown

- .golangci.yml
- pkg/common/resource_utils/autoscaler.go
- pkg/common/resource_utils/autoscaler_test.go
- pkg/common/resource_utils/metadata.go
- pkg/common/resource_utils/metadata_test.go
- pkg/common/resource_utils/statefulset.go
- pkg/common/resource_utils/statefulset_test.go
- pkg/k8sutils/k8sutils.go
- pkg/k8sutils/k8sutils_test.go
- pkg/k8sutils/load/load.go
- pkg/k8sutils/load/load_test.go
- pkg/k8sutils/load/metadata.go
- pkg/k8sutils/load/metadata_test.go
- pkg/k8sutils/templates/object/meta.go
- pkg/k8sutils/templates/object/meta_test.go
- pkg/k8sutils/templates/pod/spec.go
- pkg/k8sutils/templates/statefulset/spec_test.go
- pkg/subcontrollers/be/be_controller.go
- pkg/subcontrollers/cn/cn_controller.go
- pkg/subcontrollers/cn/cn_controller_test.go
- pkg/subcontrollers/cn/cn_mysql.go
- pkg/subcontrollers/cn/cn_mysql_test.go
- pkg/subcontrollers/cn/cn_pod.go
- pkg/subcontrollers/fe/fe_controller.go
When a scale-in operation happens:
For BE with shared-nothing deployment, the cleanup actions include:
1. Decommission operation (time-consuming)
2. Stop pod operation (need to wait for termination of BE pod)
4. Drop BE from SR
For CN with shared-data deployment, the cleanup actions include:
1. Stop pod operation (need to wait for termination of CN pod)
2. Drop CN from SR
Among them, `Decommission` and `Stop pod` are time-consuming operations, and the Operator cannot wait for the operation to complete in a blocking manner.
In summary, the cleanup actions `Stop pod` and `Drop node` are likely not in the same tuning loop. Therefore, we cannot rely on whether the current operation is a scaling-in operation to execute these logics.
At the end of each tuning cycle, the operator performs the …
> [Enhancement] Detect scale-in and drop CN node from FE

- pkg/common/hash/hash_test.go
- pkg/common/resource_utils/statefulset.go
- pkg/common/resource_utils/statefulset_test.go
> [BugFix] When calculating the hash value of sts, persistentVolumeClaimRetentionPolicy should be included

- pkg/common/resource_utils/service.go
- pkg/controllers/starrockswarehouse_controller.go
- pkg/k8sutils/templates/object/meta.go
- pkg/k8sutils/templates/object/meta_test.go
- pkg/k8sutils/templates/statefulset/spec.go
- pkg/subcontrollers/cn/cn_controller.go
- pkg/subcontrollers/cn/cn_controller_test.go
- pkg/subcontrollers/cn/cn_pod.go
1. rename field. AliasName is not a good name, and rename it to SubResourcePrefixName.
2. Use the correct warehouse name in FE(should replace - to _)
> [BugFix] Use the correct warehouse Name in FE

- helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml
- helm-charts/charts/kube-starrocks/values.yaml
- helm-charts/charts/warehouse/templates/starrockswarehouse.yaml
- helm-charts/charts/warehouse/values.yaml
Support persistentVolumeClaimRetentionPolicy in warehouse Helm Chart
> [Enhancement] support persistentVolumeClaimRetentionPolicy in warehouse Helm Chart

- config/crd/bases/starrocks.com_starrockswarehouses.yaml
- deploy/starrocks.com_starrockswarehouses.yaml
- pkg/apis/starrocks/v1/starrockswarehouse_types.go
Rename the short name for warehouse, so that we can do like this:
```
➜  kubectl get warehouses
NAME   STATUS    REASON
wh-1   running
```
> [BugFix] Rename the short name for warehouse

- .gitignore
- pkg/apis/starrocks/v1/load_type.go
- pkg/k8sutils/templates/pod/spec.go
- pkg/k8sutils/templates/pod/version_compare.go
- pkg/k8sutils/templates/pod/version_compare_test.go
If users are using older versions of the BE/CN Image, data loss may occur if the container is restarted (for example, upgrading the container image or changing environment variables) during parallel data import. This error is caused by the graceful shutdown parameter `-g` added in `stop_cn.sh` or `stop_be.sh`. Therefore, we have modified the default preStop configuration. The strategy is as follows:
1. For shared-data mode: versions lower than 3.3.17, 3.4.6, and 3.5.2.
2. For shared-nothing mode: versions lower than 3.3.19, 3.4.8, and 3.5.6.
When users use these older versions, the `-g` parameter will no longer be added to the default preStop parameters.
> [BugFix] Remove -g parameter for some lower SR versions

- pkg/controllers/starrockscluster_controller.go
When a user provides a wrong StarRocksCluster Object, mainly because it does not contain the FE Spec section, for example:
```
apiVersion: starrocks.com/v1
kind: StarRocksCluster
metadata:
name: bee
spec:
starRocksBeSpec:
image: starrocks/be-ubuntu:3.5.6
replicas: 1
requests:
cpu: 1
memory: 1Gi
beEnvVars:
- name: FE_SERVICE_NAME
value: 10.244.0.18
args:
- "$(FE_SERVICE_NAME)"
```
It will cause the null pointer error which make operator can not work.
> [BugFix] Fix null pointer error when FE spec is missing
